apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
data:
  GMAIL_EMAIL: {{ .Values.mail.email | quote }}
  GMAIL_APP_PASSWORD: {{ .Values.mail.appPassword | quote }}
