apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
stringData:
  GMAIL_EMAIL: {{ .Values.mail.email | quote }}
  GMAIL_APP_PASSWORD: {{ .Values.mail.appPassword | quote }}
