apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
